# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../python/px4shell.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(463, 355)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        Dialog.setAutoFillBackground(False)
        self.SerialPortLabel = QtWidgets.QLabel(Dialog)
        self.SerialPortLabel.setGeometry(QtCore.QRect(180, 80, 150, 31))
        self.SerialPortLabel.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        self.SerialPortLabel.setFont(font)
        self.SerialPortLabel.setObjectName("SerialPortLabel")
        self.PortList = QtWidgets.QListWidget(Dialog)
        self.PortList.setGeometry(QtCore.QRect(100, 120, 241, 71))
        self.PortList.setObjectName("PortList")
        self.PortConnectButton = QtWidgets.QPushButton(Dialog)
        self.PortConnectButton.setGeometry(QtCore.QRect(180, 200, 75, 30))
        self.PortConnectButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        self.PortConnectButton.setFont(font)
        self.PortConnectButton.setObjectName("PortConnectButton")
        self.CurrentSerialPortLabel = QtWidgets.QLabel(Dialog)
        self.CurrentSerialPortLabel.setGeometry(QtCore.QRect(90, 250, 251, 31))
        self.CurrentSerialPortLabel.setText("")
        self.CurrentSerialPortLabel.setObjectName("CurrentSerialPortLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PX4 Forensic"))
        self.SerialPortLabel.setText(_translate("Dialog", "Serial Port 목록"))
        self.PortConnectButton.setText(_translate("Dialog", "연결"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
